services:
  - type: web
    name: cursed-cards-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: CLIENT_URL
        value: https://client-q14gyw2lr-apoorv1316s-projects.vercel.app
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
